### ISSUE TITLE
Add query data error handling to datasource-http example

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana-plugin-examples#109]
After merging https://github.com/grafana/grafana-plugin-sdk-go/pull/544 we should include query data error handling in datasource examples. Similar to https://github.com/grafana/grafana-plugin-examples/issues/108

**An example of a core plugin that needs to improve it's error handling to work properly with 207 responses:**
- https://github.com/grafana/grafana/blob/main/public/app/features/plugins/sql/datasource/SqlDatasource.ts#L167
- Currently the "save & test" will be "green" / "ok" even if the database responds with an error https://github.com/grafana/grafana/discussions/48975

**Comment by leventebalogh** [comment]
@xnyo do you think this is closable? (as https://github.com/grafana/grafana-plugin-examples/pull/119 is merged)
