### ISSUE TITLE
Unable to add icon to side nav menu item while developing app plugin

### ISSUE THREAD

**Issue by Aishwarya995** [grafana/grafana-plugin-examples#120]
I'm creating an app plugin following the example app-basic at https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-basic

I have used "icon": "cog" in the includes section in plugin.json for a menu item but the icon did not show up. Here is my plugin.json

{
  "$schema": "https://raw.githubusercontent.com/grafana/grafana/master/docs/sources/developers/plugins/plugin.schema.json",
  "type": "app",
  "name": "Another Navigation",
  "id": "side-nav-app",
  "info": {
    "keywords": ["basic", "app", "example"],
    "description": "A basic side nav app plugin",
    "author": {
      "name": "Your name"
    },
    "logos": {
      "small": "img/logo.svg",
      "large": "img/logo.svg"
    },
    "screenshots": [],
    "version": "%VERSION%",
    "updated": "%TODAY%"
  },
  "includes": [
    {
      "type": "page",
      "icon": "cog",
      "name": "Reports",
      "path": "d/1B03Q_F4k/reportee-coverage-details?orgId=1",
      "role": "Admin",
      "addToNav": true,
      "defaultNav": false
    }
  ],
  "dependencies": {
    "grafanaDependency": ">=9.2.1",
    "plugins": []
  }
}

Here the configuration item has an icon which is what I'm trying to achieve.
<img width="514" alt="Screenshot 2022-12-16 at 3 28 32 PM" src="https://user-images.githubusercontent.com/58066198/208094238-2ecd8697-7f4c-45b1-b9a4-e2611c4d6041.png">

My grafana version is 9.2.0. I have tried in the latest version too and it remains the same.

**Comment by academo** [comment]
Icons can only be added to the main menu item and not sub items
