### ISSUE TITLE
Docs: Improve documentation for the examples

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#125]
This is an Epic issue where we track progress of which examples has proper documentation. @leventebalogh has written a really good documentation for the [basic app example](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-basic), so please use that as reference when adding documentation to an example.

https://github.com/grafana/grafana-plugin-examples/issues/125#tasklist-block-81cda363-994f-4091-bea2-eb53eaff2986

**Comment by sympatheticmoose** [comment]
believe this is covered elsewhere
