### ISSUE TITLE
Problem Running examples/datasource-basic

### ISSUE THREAD

**Issue by haeferer** [grafana/grafana-plugin-examples#170]
Hi, 

first of all, this is a very cool projekt. I've tried the basic examples for a datasource plugin, but it seems the code is not working.

My findings:

Current pipeline seems to not compile the ts-files into the dist directory (grafana Webseite answers plugin with 404 - module.js not found)

Maybe there are some changes to the BuildPipeline

If somebody can give me a hint according the pipeline i can try to fix it.

(PS : it does not work with npm an yarn)

Thx for your great work

Andreas

**Comment by pop1989bb** [comment]
Hi,
I can confirm. I tried different ways to get the examples working.
At the end I was able to have "apparently" a compiled plugin but then grafana only displayed the message 
`Unable to dynamically transpile ES module System.config({ transpile: 'transpile-module'})`

**Comment by academo** [comment]
Hi @haeferer and @pop1989bb thanks for your report.

I tested the basic datasource example and it is working just as expected. Things to keep in consideration:

* If you are using windows, compile using WSL. The [tooling](https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin/#grafana--create-plugin) that builds grafana plugins doesn't support windows natively.
* Run `yarn build` first before you start the server (`yarn server`) if you build the plugin after, then you should restart the grafana server. This is only for the first time you load the plugin, once grafana loads the plugin the first time you don't need to restart it when you build your plugin.
