### ISSUE TITLE
Use grafana/ui components in examples rather than referring to gf class names

### ISSUE THREAD

**Issue by marefr** [grafana/grafana-plugin-examples#173]
Use grafana/ui components in examples rather than referring to gf class names. Below an example that are using gf-classes and should be able to use [forms components](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-form--async-validation):
https://github.com/grafana/grafana-plugin-examples/blob/a57c63cf9211df73b66bb0eb5f937b39262ffded/examples/datasource-http-backend/src/components/ConfigEditor.tsx#L14-L22

**Comment by sympatheticmoose** [comment]
Couple of potential follow ups:
- validator check regex on this
- updates to docs to point towards correct components for styling
