### ISSUE TITLE
Not able to build the plugins on Windows

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana-plugin-examples#184]
### What happened?

I am trying to build and test app template plugins (app-with-datasource) but I am not able to do that.
I am able to build the backend, but the UI I am not able to.

```cmd
[app-with-backend][master] > yarn build
yarn run v1.22.19
warning ..\..\..\..\..\..\package.json: No license field
$ webpack -c ./.config/webpack/webpack.config.ts --env production
assets by path *.md 195 bytes
  asset README.md 143 bytes [compared for emit] [from: README.md] [copied]
  asset CHANGELOG.md 52 bytes [compared for emit] [from: ../CHANGELOG.md] [copied]
asset LICENSE 11.1 KiB [compared for emit] [from: ../LICENSE] [copied]
asset img/logo.svg 1.55 KiB [compared for emit] [from: img/logo.svg] [copied]
asset plugin.json 1.05 KiB [emitted] [from: plugin.json] [copied]
webpack 5.88.2 compiled successfully in 12708 ms
Done in 19.27s.
```

I don't see the ts/x files getting compiled and exported as module.js

### Environment (with versions)?
Platform: Windows 10
Node: 18.16.0
Go: 1.19.5 windows/amd64

**Comment by academo** [comment]
Hi @Bujupah native windows is not supported. Please use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by Bujupah** [comment]
thanks @academo, is there any plans to support windows without wsl?
any ongoing topic I can follow to track that?

**Comment by academo** [comment]
@Bujupah there are no plans to support native windows. We follow the same supported environment for grafana development which also only works in WSL.

**Comment by Bujupah** [comment]
Gotcha! thanks for the update.
