### ISSUE TITLE
app plugin as middleware or auth

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana-plugin-examples#186]
I am planning to create such plugin, but I want a lookup and thought from an expert.

Plugin should be capable of handling authentication - (maybe create a boilerplate to handle any custom authentication)
Plugin should be able to act as a middleware - for example to handle authorization.

This will require small change in grafana I know but what do you guys think of this?

**Comment by academo** [comment]
Hi @Bujupah It is best to post general grafana plugin development questions in our community forum here https://community.grafana.com/c/plugin-development/30
