### ISSUE TITLE
streaming-websocket unclear

### ISSUE THREAD

**Issue by OlivierCodeC** [grafana/grafana-plugin-examples#2]
As a beginner, I do not make it work.

streaming-websocket-plugin is set as a "panel" in the plugin.json, it should be "datasource" ?

Even I put "datasource" in plugin.json and it is added as datasource in the datasource manager of grafana. Once on creates a new panel, grafana cannot choose it in the data sources combobox.

What did I miss ?

**Comment by faxm0dem** [comment]
I wrote a similar plugin then I found this example here.
Maybe my code can help : https://github.com/faxm0dem/grafana-riemann-websocket-datasource/
