### ISSUE TITLE
Add example how to use adhoc features with React in datasource 

### ISSUE THREAD

**Issue by Slach** [grafana/grafana-plugin-examples#216]

**Comment by academo** [comment]
@Slach can you please expand this issue and elaborate what do you mean by `adhoc features` ?

**Comment by mckn** [comment]
@Slach are you requesting an example of how you support adhoc template variables in a datasource?

**Comment by Slach** [comment]
i mean if we have adhoc template variables which have source data from datasource and passthru it back to QueryEditor for example

**Comment by mckn** [comment]
@Slach super! Do you mind updating the issue with some more details and maybe a written example of what you are looking for? It would help us start working on this sooner rather than later.

**Comment by sunker** [comment]
@Slach we'll look into this as soon as you provide more details. 

In the meantime, FWIW, [here](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-an-interval-variable) a link to the adhoc documentation. To add support for adhoc filter in your data source, you need to implement the [getTagKeys](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L290) method in the data source file. [This](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L667-L696 ) is an example of what it looks like in the prometheus data source.

**Comment by marefr** [comment]
Sounds like you've got all the information you need @Slach. Closing the issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information, if needed.
