### ISSUE TITLE
Reopening websocket connection

### ISSUE THREAD

**Issue by sscots** [grafana/grafana-plugin-examples#22]
How can the websocket plugin handle when a websocket is closed and reopened...without reloading the grafana panel?
Simply calling query() again doesn't seem to continue populating the chart. I feel like I need to reload the DataSource instance.
I'd like it to work similar to when you change the time range option at the top.

**Comment by academo** [comment]
Hi @sscots it is best to ask questions related to plugin development in our community forum https://community.grafana.com/c/plugin-development/30
