### ISSUE TITLE
app-with-backend run err

### ISSUE THREAD

**Issue by huozhirui** [grafana/grafana-plugin-examples#222]
I allow an example like this to report an error
![image](https://github.com/grafana/grafana-plugin-examples/assets/55824382/499303fa-0181-4c36-9110-39179f88aaf4)
<img width="1032" alt="image" src="https://github.com/grafana/grafana-plugin-examples/assets/55824382/f9a51bba-47b5-475a-8394-c6357176f8b8">

**Comment by wbrowne** [comment]
Hi @huozhirui,

Can you please provide some more information about how you encountered this issue. For example:
- What Grafana version you are running
- What page you visited to encounter this error

Could you also provide full backend logs and a list of the contents of the plugin directory. It appears as though maybe the plugin backend is not running / not functioning correctly. Please also share the response for http://localhost:3000/api/plugins/myorg-withbackend-app/health if possible.

**Comment by huozhirui** [comment]
It should be that I accessed the URL incorrectly. It has been resolved. Thank you
