### ISSUE TITLE
How can Grafana allow Editor to view loaded app plugins

### ISSUE THREAD

**Issue by huozhirui** [grafana/grafana-plugin-examples#232]
I developed an app plugin and found a problem. I can use it normally under the admin user, but the Editor user cannot see this plugin in the menu bar. How should I solve this problem
```[tasklist]
### Tasks
```

**Comment by marefr** [comment]
@huozhirui please provide more information such as a link to the source code of your plugin and/or your plugin.json together with what Grafana version you're using - have you for example tried the latest stable Grafana version?

**Comment by huozhirui** [comment]
> @huozhirui please provide more information such as a link to the source code of your plugin and/or your plugin.json together with what Grafana version you're using - have you for example tried the latest stable Grafana version?

grafana version: 9.3.1 
![image](https://github.com/grafana/grafana-plugin-examples/assets/55824382/727947d2-4196-4a77-9710-a8baa06ac8e0)

**Comment by marefr** [comment]
Grafana v9.3.1 is a very old version. If this would have been a problem of recent versions a lot more users would have reported this problem. Would suggest you to try more recent versions, see https://grafana.com/grafana/download:
- v9.3.16 (still very old, but latest patch of your current minor version, v9.3.x)
- v9.4.17
- v9.5.14
- v10.2.2 (the latest stable Grafana version)

I'm going to close this for now. If you test on above versions and you still experience the same problem let us know and we'll reopen it.
