### ISSUE TITLE
Include docker-compose files into script which updates grafana versions

### ISSUE THREAD

**Issue by Ukochka** [grafana/grafana-plugin-examples#285]
When run update-grafana-version script it checks package.json and package-lock.json files, but also it should update docker-compose files with grafana versions

**Comment by tolzhabayev** [comment]
As discusses in the weekly, we should adjust the script to do the following:
- Update [the part that updates the dependencies](https://github.com/grafana/grafana-plugin-examples/blob/c8e65dcaac8e2aa9d8db51d7eab695f46f0d3d93/scripts/update-grafana-version.sh#L9-L64) into looping over examples and using `npx @grafana/create-plugin@latest update`
- Check if we also update docker-compose file if not [keep the section](https://github.com/grafana/grafana-plugin-examples/blob/main/scripts/update-grafana-version.sh#L83-L98) as it is for now until we find a way to do it properly in the create-plugin update command
- Once the script is working with the new command create a github action workflow to do the updates on a schedule (exact schedule to be defined - we can start `monthly`)
- The github action workflow should auto merge if all tests are green
