### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by sunker** [grafana/grafana-plugin-examples#300]
We need some way automating dependency updates in this repo. The [dependabot conf](https://github.com/grafana/grafana-plugin-examples/blob/84856557d88812ea4335026c3db7daf98de1da34/.github/dependabot.yml) that we currently have is not working becauase the paths to the example plugins are incorrect. 

Some requirements:
* New plugin examples should be picked up automatically and not require changes in the config (basically supporting wildcards or globs)
* Should support dependency group updates so that we can update for example all grafana packages at once. 
* Since this is not a mono repo, many of the dependencies are duplicated across the examples. It would be good if version bumps to one dependency (or a group of dependencies) where gathered in one PR and not one PR per example plugin
* It would be good if config allowed for certain dependencies to be updated more frequently than others. For example, a PR for updating plugin-e2e should be raised as soon as there's a new version, whereas other deps may not need to be updated as frequently. 

It's my understanding that Dependabot is not flexible enough to cater for the requirements above, so I'm gonna look into replacing it with Renovate.

**Comment by tolzhabayev** [comment]
You could collaborate with @Ukochka on this

**Comment by sunker** [comment]
Closing this issue as we have agreed to not use Renovate to keep our example plugins up to date, but instead schdule the create-plugin `update` to run. @Ukochka is working on this.
