### ISSUE TITLE
How front-end plugins solve cross domain problems

### ISSUE THREAD

**Issue by huozhirui** [grafana/grafana-plugin-examples#323]
How front-end plugins solve cross domain problems
![image](https://github.com/grafana/grafana-plugin-examples/assets/55824382/06ab5a31-3ed6-4a86-8f7c-3d02bed41e8f)

I configured HTTP proxy middleware, but it did not take effect
<img width="1324" alt="image" src="https://github.com/grafana/grafana-plugin-examples/assets/55824382/f8e0473a-3b2b-4b96-9f88-49373df12e6f">

**Comment by tolzhabayev** [comment]
@huozhirui please take a look at our data proxy documentation, it might clear things up https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/fetch-data-from-frontend

**Comment by tolzhabayev** [comment]
Resolving due to inactivity and docs around how to solve those problems. Feel free to reopen in case something is unclear.
