### ISSUE TITLE
Examples: Add example for how to do a simple http-datasource (with backend)

### ISSUE THREAD

**Issue by mckn** [grafana/grafana-plugin-examples#86]
The current example for the http-datasource is implemented as a frontend only datasource plugin. This is something we support but I'm not sure we should provide this as an example. Writing a datasource plugin like this has a couple of drawbacks:

1. You won't be able to support alerting since those queries needs to be executed in the backend.
2. If you need to send requests to an API that requires some kind of credentials they will be available in the browser.
3. You won't be able to support expression queries since those are executed in the backend.

With that said I think we should add another example as a datasource plugin with a backend. Maybe update the readme for the current http-datasource example where we highlight when it is applicable to use a frontend-only datasource and what drawbacks it has.

**Comment by andresmgot** [comment]
there is one now: https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-http-backend
